config/routes.rb
Rails.application.routes.draw do
    root 'static#index'
    get 'static/index' => 'static#index'
    get 'static/about' => 'static#about'
    get 'index' => 'static#index'

    get     '/auth/:provider/callback', to: 'sessions#create'
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    
    
    resources :album do
        get "delete"
    end
    get 'albums/search' =>   'album#search'
    get 'albums/addAlbum', to: 'album#addAlbum'   
    post 'albums/updateRowOrder', to: 'album#updateRowOrder'   

    resources :track do
        get "delete"
    end    
    
    get 'album_listing/numbered' => 'album_listing#numbered'
    get 'album_listing/unnumbered' => 'album_listing#unnumbered'    
    resources :album_listing
    
    delete 'album_listing/delete' => 'album_listing#destroy'

    get   'card/edit' => 'card#edit'
    patch 'card/'     => 'card#update'
    get   'card'      => 'card#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
    belongs_to :user
    has_many :tracks, -> { order 'track_number ASC' }
    has_one :album_listing, :dependent => :destroy

    def image
        if (!self[:image].nil?) and 
            (!self[:image].empty?) and
            (checkImageExists(self[:image]))
            return self[:image]
        end
        return "no_image.png"
    end
    
    def small_image
        if (!self[:small_image].nil?) and 
            (!self[:small_image].empty?) and 
            (checkImageExists(self[:small_image]))
            return self[:small_image]
        end
        return "no_image_small.png"
    end
    
    # Search Last.fm for an album and return an array of results.
    def self.searchLastFM(term)
        term = I18n.transliterate(term)
    
        url = 'http://ws.audioscrobbler.com/2.0/?method=album.search&album=' + term.to_s + '&api_key=' + ENV['LAST_FM_API_KEY'].to_s + '&limit=20&format=json'   
                
        response = getJSONResponse(url)
        
        results =[]
        position = 0
        response['results']['albummatches']['album'].each do |a|
            results[position] = Album.new( :artist => a['artist'], :title => a['name']) 
            position += 1
        end
        results
    end
    
    # Search Last.fm for a specific album, create a new Album object from the response and return it.
    def self.getAlbumFromLastFM(artist, album)
        artist = I18n.transliterate(artist)
        album = I18n.transliterate(album)
    
        url = 'http://ws.audioscrobbler.com/2.0/?method=album.getInfo&album=' + album.to_s + '&artist=' + artist.to_s + '&api_key=' + ENV['LAST_FM_API_KEY'].to_s + '&format=json'
        
        response = getJSONResponse(url)
        
        imgUrl = ""
        imgSize = 0
        smImgUrl = ""
        smImgSize = 0
        response['album']['image'].each do |i|
            case i['size']
                when "small"
                    currentSize=2
                when "medium"
                    currentSize=3
                when "large"
                    currentSize=4
                when "extralarge"
                    currentSize=5
                when "mega"
                    currentSize=6
                else
                    currentSize=1
            end
            if currentSize > imgSize
                imgUrl = i['#text']
                imgSize = currentSize
            end
            if currentSize < smImgSize or smImgSize == 0
                smImgUrl = i['#text']
                smImgSize = currentSize
            end
        end
                
        tracks = []
        position = 0
        response['album']['tracks']['track'].each do |t|
            rank = t["rank"]
            if (rank == nil) 
                rank = t["@attr"]["rank"]
                if (rank == nil) 
                    rank = position
                end
            end
            tracks[position] = Track.new(:track_number => rank, :track_name => t["name"])
            position += 1
        end         
        
        Album.new(  :title           =>  response['album']['name'],
                    :artist          =>  response['album']['artist'],
                    :image           =>  imgUrl,
                    :small_image     =>  smImgUrl,
                    :tracks          =>  tracks )
    end
    
    # Move a tracks position in the track listing of an album, update other tracks to maintain the track listing.
    def updateTrackOrder(movedTrack, newPosition)
        tracklist = tracks.order('tracks.track_number ASC').all
        position = 1
        tracklist.each do |t|
            if t.id != movedTrack.id 
                if newPosition == position
                    movedTrack.track_number = position
                    movedTrack.save()
                    position += 1
                end 
                t.track_number = position
                position += 1
                t.save()
            end
        end
    end
        
    # Update all track numbers to ensure listing from 1->x and fix errored numbering from Last.fm.
    def normaliseTrackOrder
        tracklist = tracks.order('tracks.track_number ASC').all
        position = 1
        tracklist.each do |t|
            t.track_number = position
            position += 1
            t.save()
        end
    end

    # Returns a array of numbered tracks for use in a table.
    def getTracksAsTable
        table = []
        tracks.each do |track|
            table.push(["#{track.track_number}.", track.track_name])
        end
        return table
    end
    
    private 
    
    def self.getJSONResponse(url)
        urlresponse = HTTParty.get(url)
        response = JSON.parse(urlresponse.body)
    end
        
    def checkImageExists(url)
        response = HTTParty.get(url)
        if response.code == 200
            return true
        end
        return false
    end 

end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
    respond_to :html, :json

    load_and_authorize_resource :except => [:search, :getAlbumFromLastFM]

    def index
    end

    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
        respond_to do |format|
            format.json do
                @album = Album.find(params[:id])
                @album.update_attributes(album_params)
                respond_with @album
            end
        end
    end

    def delete
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy
    end

    def delete
        @album = Album.find(params[:album_id])
    end
    
    # Search Last.fm for a list of albums matching the search term, return them as a JSON list.
    def search
        respond_to do |format|
            format.json do
                albums = Album.searchLastFM(params[:term])
                
                jsonOut =[]
                position = 0
                albums.each do |a|
                    jsonOut[position] = { "label" => a.artist + ' - ' + a.title, "value" => a.title } 
                    position += 1
                end
                render :json => jsonOut.to_json
            end        
        end
    end
    
    # Get album data from Last.fm and create a new album. Save the new album to the database.
    def addAlbum
        respond_to do |format|
            format.json do
                album = Album.getAlbumFromLastFM(params[:artist], params[:album])
                album.user_id = current_user.id
                album.save()
                render :json => album.as_json(include: :tracks)
            end        
        end
    end
    
    # Change a tracks position on an album.
    def updateRowOrder
        respond_to do |format|
            format.json do
                puts (:params)
                movedTrack = Track.find(params[:track][:track_id])
                newPosition = params[:track][:row_order_position].to_i
                newPosition += 1 #jQuery is 0 indexed, our albums are 1 indexed
                album = movedTrack.album
                album.updateTrackOrder(movedTrack, newPosition)
                render :json => album.as_json(include: :tracks)
            end        
        end
    end
        
    private     
    def album_params
        params.require(:album).permit(:title, :artist)
    end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/views/album/_delete.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3>Delete Album</h3>
        </div>
        <div class="modal-body">
            <ul class="errors"></ul>
            Are you sure you wish to delete <b><%= @album.title %></b> by <b><%= @album.artist %></b>?
        </div>
        <div class="modal-footer">
            <%= link_to "Yes", album_path(@album), method: :delete, remote: true, class: "btn btn-danger" %>
            <%= link_to "No", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
        </div>
    </div>
</div>

app/views/album/_trackrow.html.erb
<tr id="track-<%=track.id%>" data-item-id=<%= "#{track.id}" %> class="item" style="<%=style%>">
    <td>
        <%= best_in_place track, :track_name, :as => :input %> 
    </td>
    <td>
        <%= link_to "<span class='fa fa-trash-o' aria-hidden='true'></span> Delete".html_safe, track_delete_path(track), remote: true, :class => "btn btn-default btn-xs pull-right" %>
    </td>
</tr>

app/views/album/addTrack.js.erb
<% if @album.errors.any? %>
    <% @album.errors.full_messages.each do |message| %>
    $("#flasher").append($("<div class='alert alert-danger alert-dismissible' />").html("<button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><span class='fa fa-exclamation-triangle' aria-hidden='true'></span> <%= message.html_safe %>"));
<% end %>
<% else %>
    $("#flasher").append($("<div style='display: none;' id='tflash-<%=@track.id %>' class='alert alert-success alert-dismissible' />").html("<button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><span class='fa fa-info' aria-hidden='true'></span> <%=@track.track_name %> added"));
    $("#tflash-<%=@track.id %>").show("blind");
    
    window.setTimeout(function() {
        $("#tflash-<%=@track.id %>").hide({
            effect: "blind",
            complete: function() {
                    $("#tflash-<%=@album.id %>").remove();
                }
            });
        }, 5000);
    
    $("#tracks<%=@album.id%> tbody").append('<%=escape_javascript(render "trackrow", track: @track, style: "display: none;")%>');
    
    $("#track-<%=@track.id%>").show({
        effect: "blind",
        complete: function() {
                $("#albums").trigger("refreshGrid");
                $(".album-<%=@album.id%>").val("");
            }
        });
<% end %>

app/views/album/delete.js.erb
$("#album-modal").html("<%= escape_javascript(render 'delete') %>")
$("#album-modal").modal("show")

app/views/album/destroy.js.erb
<% if @album.errors.any? %>
    <% @album.errors.full_messages.each do |message| %>
    $("#flasher").append($("<div class='alert alert-danger alert-dismissible' />").html("<button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><span class='fa fa-exclamation-triangle' aria-hidden='true'></span> <%= message.html_safe %>"));
<% end %>
<% else %>
    $("#flasher").append($("<div style='display: none;' id='flash-<%=@album.id %>' class='alert alert-success alert-dismissible' />").html("<button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><span class='fa fa-info' aria-hidden='true'></span> <%=@album.title %> deleted"));
    $("#flash-<%=@album.id %>").show("blind");
    
    window.setTimeout(function() {
        $("#flash-<%=@album.id %>").hide({
            effect: "blind",
            complete: function() {
                    $("#flash-<%=@album.id %>").remove();
                }
            });
        }, 5000);
    
    $("#album-<%=@album.id %>").hide({
        effect: "puff",
        complete: function() {
                $("#album-<%=@album.id %>").remove();
                $("#albums").trigger("refreshGrid");
            }
        });
        
    $("#album-modal").modal("hide");
<% end %>

app/views/album/index.html.erb
<script type="text/javascript">
    $(function() {
        //Arranges Cards
        $('#albums').freetile({
            animate: true,
            elementDelay: 0,
            customEvents: "refreshGrid"
        });
        //Sets up sortable track listing on card body
        $('.sortable tbody').sortable({
            axis: "y",
            update: function( event, ui ) {
                item_id = ui.item.data('item-id')
                console.log(item_id)
                position = ui.item.index()
                $.ajax({
                    type: 'POST',
                    url: '/albums/updateRowOrder',
                    dataType: 'json',
                    data: { track: {track_id: item_id, row_order_position: position } }
                })
            }
        });
    });
    
</script>

<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <h2>
                Modify Albums
            </h2>
            <p>
                Below is the collection of all the albums that are in your library. Use this screen to make any changes to the albums before they go to print.
            </p>
        </div>
    </div>
</div>

<ul id="albums" style="list-style: none;">
    <% @albums.each do |a| %>
        <li id="album-<%=a.id%>" style="width:300px;" >
            <div class="thumbnail">
                <%= image_tag a.image, alt: a.title, class: "albumBoxImage"%>
                <div class="caption">
                    <hr/>
                    <h3>
                        <%= best_in_place a, :title, :as => :input %> 
                    </h3>
                    <b>
                        <%= best_in_place a, :artist, :as => :input %> 
                    </b>
                    <div class="btn-group btn-group-justified" role="group" aria-label="controls">
                        <div class="btn-group" role="group">
                            <%= link_to "<span class='fa fa-trash-o' aria-hidden='true'></span> Delete".html_safe, album_delete_path(a), remote: true, class: "btn btn-default btn-xs" %>
                        </div>
                    </div>    
                    <hr/>
                    <table class="table table-bordered table-striped sortable" id="tracks<%=a.id%>">
                        <tbody>
                            <% a.tracks.each do |t| %>
                                <%= render "trackrow", track: t, style: ""%>
                            <% end %>
                        </tbody>
                    </table>
                    <div class="container-fluid">
                        <%= form_tag "/track", :method => "post", :class => "form-inline", :remote => true do %>
                            <%= hidden_field_tag "album_id", a.id %>
                            <div class="form-group form-group-sm">
                                <label class="sr-only" for="track_name">Add Track</label>
                                <%= text_field_tag "track_name", nil, placeholder: "Add Track", class: "form-control album-" + a.id.to_s %>
                            </div>
                            <div class="form-group form-group-sm">
                                <button type="submit" name="commit"  class="btn btn-primary btn-block btn-sm"><span class='fa fa-plus-circle' aria-hidden='true'></span></input>    
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </li>
    <% end -%>
</ul>

<div id="album-modal" class="modal fade"></div>

app/views/album/new.html.erb
<script type="text/javascript">
    $(function() {
        $( "#title_search" ).autocomplete({
            source: "/albums/search",
            search: function() {
                $("#loading").show();
            },
            response: function() {
                $("#loading").hide();
            },
            select: function( event, ui ) {
                $("#loading").show();
                values = ui.item.label.split('-')
                path = "/albums/addAlbum"
                query = "?artist=" + encodeURIComponent(values[0].trim()) + "&album=" + encodeURIComponent(values[1].trim())
                
                var albumdetails = $.getJSON( path + query )
                    .done(function( data ) {
                        temp = $("#album_template").clone();
                        temp.attr("id", data.title + "_" + data.artist)
                        temp.find("#album").append(data.title);
                        temp.find("#artist").append(data.artist);
                        temp.find("#image").attr("src", data.image);
                        
                        data.tracks.forEach(function (item, index) {
                            temp.find("#tracks").append("<li>" + item.track_name + "</li>");
                        });
                        
                        //temp.show();
                        $("#added_albums").prepend(temp);
                        $("#added_albums").trigger( "refreshGrid");
                        $("#title_search").val("");
                        
                        $.bootstrapPurr("<b>Added: </b>" + data.title, {
                            type:'info',
                                offset: {
                                    amount: 60,
                                    from: 'top'
                                }
                            });
                    })
                    .fail(function(xhr, ajaxOptions, thrownError) {
                            $.bootstrapPurr("<b>An Error Occurred: </b>" + thrownError, {
                            type:'danger',
                                offset: {
                                    amount: 60,
                                    from: 'top'
                                }
                            });
                    })
                    .always(function() {
                        $("#loading").hide();
                    });
            }
        });
        $('#added_albums').freetile({
            animate: true,
            elementDelay: 0,
            customEvents: "refreshGrid",
            persistentCallback: true,
            callback: function () {
                $("#added_albums").children(".album_box").each(function() {
                    if (!$(this).is(":visible")) {
                        $(this).show("blind"); 
                    }
                });
            }
        });
    });
</script>

<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <h2>
                Add Albums
            </h2>
            <p>
                Use the text box below to search for an Album, select the one you want from the list and it'll be added to your library.
                
                You can modify Album info on the 'Manage Albums' page.
            </p>
        </div>
    </div>
</div>

<div class="container-fluid">
    <fieldset class="form-group row">
            <input id="title_search" class="form-control", placeholder="Album Title" %>
            <span id="loading" class='fa fa-circle-o-notch fa-spin fa-fw' aria-hidden='true' style="display: none;"></span>
    </fieldset>
</div>

<hr/>
<ul id="added_albums" style="list-style: none;">
</ul>

<ul>
    <li id="album_template" class="album_box" style="display: none; width:300px;" >
        <div class="thumbnail">
            <img id = "image" alt="Album Cover" class="albumBoxImage"/>
            <div class="caption">
                <h3><span id = "album"></span> - <span id = "artist"></span></h3>
                <ul id = "tracks">
                </ul>
            </div>
        </div>
    </li>
</ul>