config/routes.rb
Rails.application.routes.draw do
    root 'static#index'
    get 'static/index' => 'static#index'
    get 'static/about' => 'static#about'
    get 'index' => 'static#index'

    get     '/auth/:provider/callback', to: 'sessions#create'
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    
    
    resources :album do
        get "delete"
    end
    get 'albums/search' =>   'album#search'
    get 'albums/addAlbum', to: 'album#addAlbum'   
    post 'albums/updateRowOrder', to: 'album#updateRowOrder'   

    resources :track do
        get "delete"
    end    
    
    get 'album_listing/numbered' => 'album_listing#numbered'
    get 'album_listing/unnumbered' => 'album_listing#unnumbered'    
    resources :album_listing
    
    delete 'album_listing/delete' => 'album_listing#destroy'

    get   'card/edit' => 'card#edit'
    patch 'card/'     => 'card#update'
    get   'card'      => 'card#index'
end

app/models/track.rb
class Track < ActiveRecord::Base
    belongs_to  :album
end

app/controllers/track_controller.rb
class TrackController < ApplicationController
    respond_to :html, :json

    load_and_authorize_resource

    def index
    end

    def show
    end

    def new
    end

    def create   
        album = Album.find(params[:album_id])
        
        album.normaliseTrackOrder
        
        track = Track.new({:track_name => params[:track_name], :track_number => album.tracks.length + 1})
        album.tracks << track
        track.save()
        album.save()  
        
        @album = album
        @track = track
    end

    def edit
    end

    def update
        respond_to do |format|
            format.json do
                puts params
                @track = Track.find(params[:id])
                @track.update_attributes(album_params)
                respond_with @track
            end
        end
    end
    
    def delete
        @track = Track.find(params[:track_id])
    end

    def destroy
        @track = Track.find(params[:id])
        @track.destroy
    end
    
    private     
    def album_params
        params.require(:track).permit(:track_name, :track_number)
    end
end

app/helpers/track_helper.rb
module TrackHelper
end

app/views/track/_delete.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3>Delete Track</h3>
        </div>
        <div class="modal-body">
            <ul class="errors"></ul>
            Are you sure you wish to delete <b><%= @track.track_name %></b>?
        </div>
        <div class="modal-footer">
            <%= link_to "Yes", track_path(@track), method: :delete, remote: true, class: "btn btn-danger" %>
            <%= link_to "No", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
        </div>
    </div>
</div>

app/views/track/create.js.erb
<% if @album.errors.any? %>
    <%=render "jsDisplayErrors", model: @album%>
<% else %>
    $.bootstrapPurr("<span class='fa fa-info' aria-hidden='true'></span> <%=@track.track_name %> added", {
                type:'success',
                    offset: {
                        amount: 60,
                        from: 'top'
                    }
                });
    
    $("#tracks<%=@album.id%> tbody").append('<%=escape_javascript(render "trackrow", track: @track, style: "display: none;")%>');
    
    $("#track-<%=@track.id%>").show({
        effect: "blind",
        complete: function() {
                $("#albums").trigger("refreshGrid");
                $(".album-<%=@album.id%>").val("");
            }
        });
<% end %>

app/views/track/delete.js.erb
$("#album-modal").html("<%= escape_javascript(render 'delete') %>")
$("#album-modal").modal("show")

app/views/track/destroy.js.erb
<% if @track.errors.any? %>
    <%=render "jsDisplayErrors", model: @album%>
<% else %>
    $.bootstrapPurr("<span class='fa fa-info' aria-hidden='true'></span> <%=@track.track_name %> deleted", {
                type:'success',
                    offset: {
                        amount: 60,
                        from: 'top'
                    }
                });
    
    $("#track-<%=@track.id %>").hide({
        complete: function() {
                $("#track-<%=@track.id %>").remove();
            }
        });
        
    $("#album-modal").modal("hide");
<% end %>